name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] #ubuntu-latest, windows-latest,

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        cmake -E make_directory ${{github.workspace}}/Runtimes

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'

    # fixes sporadic build fails on Windows (https://github.com/actions/setup-dotnet/issues/155)
    # - name: Clean
    #   run: dotnet clean -c Release && dotnet nuget locals all --clear

    - name: Hack rpath
      working-directory: ${{github.workspace}}/External/OpenImageDenoise
      run: |
        otool -l libOpenImageDenoise.1.dylib
        install_name_tool -add_rpath @loader_path/ libOpenImageDenoise.1.dylib
        otool -l libOpenImageDenoise.1.dylib

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        dotnet test
        DYLD_PRINT_LIBRARIES=YES dotnet run -p SimpleImageIO.Integration

    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}/Runtimes/*

  pack:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: ${{github.workspace}}/Runtimes

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'

    # fixes sporadic build fails on Windows (https://github.com/actions/setup-dotnet/issues/155)
    - name: Clean
      run: dotnet clean -c Release && dotnet nuget locals all --clear

    - name: Pack
      run: dotnet pack -c Release

    - name: Upload .nupkg
      uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}/SimpleImageIO/bin/**/*.nupkg

    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: SimpleImageIO/SimpleImageIO.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

  testpython:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Fetch Python build dependencies
        run: python -m pip install --user wheel

      - name: Build and install
        run: python setup.py install

      - name: Run tests
        working-directory: ${{github.workspace}}/PyTest
        run: python -m unittest

  pypi:
    runs-on: ubuntu-latest
    needs: [testpython]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Fetch Python build dependencies
        run: python -m pip install --user wheel

      - name: Build Python Wheel
        run: python setup.py sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
